.gitignore
package-lock.json
package.json

Feature compodoc

---

src/app/pages/task/task-form/task-form.component.html

Adjusting the status and the time spent  fields on the task form

---

package-lock.json
src/app/pages/home/recent-tasks/recent-tasks.component.html
src/app/pages/home/recent-tasks/recent-tasks.component.scss
src/app/pages/project/user-project-dashboard/user-project-dashboard.component.html
src/app/pages/project/user-project-dashboard/user-project-dashboard.component.scss

Closes #34  
Now, the label stay fixed, and only the card's container goes to the left.

fixed label in containers

---

package-lock.json
src/app/pages/home/recent-tasks/recent-tasks.component.html
src/app/pages/home/recent-tasks/recent-tasks.component.scss
src/app/pages/project/user-project-dashboard/user-project-dashboard.component.html
src/app/pages/project/user-project-dashboard/user-project-dashboard.component.scss
src/app/pages/task/task-form/task-form.component.html
src/app/pages/task/task-form/task-form.component.scss
src/app/pages/task/task-form/task-form.component.ts

Closes #35 
Before loading teams:
After choosing team:
If team doesnt have projects:

Feature link novo project

---

package-lock.json
src/app/core/services/base.service.ts
src/app/core/services/invitation.service.ts
src/app/core/services/project.service.ts
src/app/core/services/task.service.ts
src/app/core/services/team.service.ts
src/app/core/services/user.service.ts
src/app/pages/signup/signup.component.ts
src/app/pages/team/team-detail/team-detail.component.ts
src/app/shared/models/base.model.ts
src/app/shared/models/invitation.model.ts
src/app/shared/models/project.model.ts
src/app/shared/models/task.model.ts
src/app/shared/models/team.model.ts
src/app/shared/models/user.model.ts

This pull request is based in creating abstraction levels to our layers in NG project.
So, I created:
- BaseModel (which has only an id, and it's necessary to use in others abstractions)
- BaseService
- receives an injector, to get injections to be used within the class.
- an path related to the resource that extends it.
- methods created: 
- `createOrUpdate()`
- `delete()`
- `findAll()`
- `findById()`
It will give us time avoing us to create boilerplate code, as common methods in service layers.
Another good point is that some of our resources (almost all of them) didn't have delete methods, so now they all have, just by inheritance. :)

Feature refactory Base classes

---

src/app/pages/task/task-form/task-form.component.html
src/app/pages/task/task-form/task-form.component.ts
src/app/shared/enums/status.enum.ts

Fixing enum status

---

src/app/pages/home/due-soon-tasks/due-soon-tasks.component.html
src/app/pages/home/due-soon-tasks/due-soon-tasks.component.scss
src/app/pages/home/projects-home/projects-home.component.html
src/app/pages/home/projects-home/projects-home.component.scss
src/app/pages/home/projects-home/projects-home.component.ts
src/app/pages/home/recent-tasks/recent-tasks.component.html
src/app/pages/home/recent-tasks/recent-tasks.component.scss
src/app/pages/project/project-form/project-form.component.html
src/app/pages/project/project-form/project-form.component.scss
src/app/pages/project/quick-project-form/quick-project-form.component.html
src/app/pages/project/user-project-dashboard/user-project-dashboard.component.html
src/app/pages/project/user-project-dashboard/user-project-dashboard.component.scss
src/gt-theme.scss

Improve style project form

---

src/app/core/services/shared.service.ts

Garanting certain specificity

---

src/app/pages/home/invitation/invitation.component.html
src/app/pages/home/invitation/invitation.component.scss

- improved a lil bit on styling and visibility
- added a link to the team
BEFORE:
AFTER:

new style in notification of team's invitation

---

src/app/pages/signup/signup.component.html
src/app/pages/task/task-card/task-card.component.html
src/app/pages/task/task-list/task-list.component.scss
src/app/pages/task/task.module.ts
src/app/shared/components/gt-tasks-carousel/gt-tasks-carousel.component.html
src/app/shared/components/gt-tasks-carousel/gt-tasks-carousel.component.scss
src/app/shared/components/gt-tasks-carousel/gt-tasks-carousel.component.ts

Improve style carousel

---

package-lock.json
src/app/pages/signup/signup.component.html
src/app/pages/task/task-card/task-card.component.html
src/app/pages/task/task-card/task-card.component.scss
src/app/pages/task/task-grid/task-grid.component.html
src/app/pages/task/task-grid/task-grid.component.ts
src/gt-theme.scss

Improve ag grid style

---

package-lock.json
src/app/pages/home/invitation/invitation.component.html
src/app/pages/home/invitation/invitation.component.scss

Ajustando estilo e responsive do invitation

---

src/app/app.component.scss
src/app/pages/home/due-soon-tasks/due-soon-tasks.component.scss
src/app/pages/kanban/kanban.component.scss
src/app/pages/project/project-info/project-info.component.html
src/app/pages/project/project-info/project-info.component.scss
src/app/pages/task/task-form/task-form.component.scss
src/app/pages/task/task-list/task-list.component.scss
src/app/pages/team/team-form/team-form.component.css
src/gt-theme.scss

Improve style project info

---

src/app/app-routing.module.ts
src/app/core/services/task.service.ts
src/app/pages/task/task-card/task-card.component.html
src/app/pages/task/task-card/task-card.component.ts
src/app/pages/task/task-form/task-form.component.html
src/app/pages/task/task-form/task-form.component.ts
src/app/shared/directives/if-creator-or-target-or-manager.directive.ts
src/app/shared/directives/logged-only.directive.ts
src/app/shared/shared.module.ts

Bala stuff

---

src/app/core/services/base.service.ts
src/app/pages/task/task-form/task-form.component.html
src/app/pages/task/task-form/task-form.component.scss
src/app/pages/task/task-form/task-form.component.ts

improving in targetuser

---

src/app/app-routing.module.ts
src/app/core/guards/task-form.guard.ts
src/app/pages/task/task-form/task-form.component.ts

Reloading if in the same route

---

src/app/pages/task/task-card/task-card.component.html
src/app/pages/task/task-card/task-card.component.scss

Adding title and ellipsis to input.
Closes #112

Improving input overflow in task card.

---

src/app/pages/task/task-form/task-form.component.html
src/app/pages/task/task-form/task-form.component.ts

Adding the mask on component

---

src/app/core/services/home-updater.service.ts
src/app/pages/home/due-soon-tasks/due-soon-tasks.component.html
src/app/pages/home/due-soon-tasks/due-soon-tasks.component.ts
src/app/pages/task/task-card/task-card.component.ts

Logic to notify due soon tasks changes

---

package-lock.json
src/app/pages/team/team-list-sidenav/team-list-sidenav.component.html
src/app/shared/pipes/gt-pipes.module.ts
src/app/shared/pipes/trunc-ellipses-text.pipe.ts

Closes #191 
To solve the problem I created a pipe that will add ellipses (...) if the name of the team is bigger than the limit size informed via parameter to the pipe.

Bugfix 191

---

package-lock.json
src/app/pages/task/task-time-spent/task-time-spent.component.ts
src/app/pages/task/task-times/task-times.component.html
src/app/pages/team/team-list-sidenav/team-list-sidenav.component.html
src/app/shared/models/time-spent.model.ts
src/app/shared/pipes/gt-pipes.module.ts
src/app/shared/pipes/trunc-ellipses-text.pipe.ts

Closes #190 
Add logic to populate time spent with firstName instead of gladname

Bugfix 190

---

package-lock.json
src/app/pages/task/task-card/task-card.component.ts
src/app/pages/task/task-form/task-form.component.ts
src/app/pages/team/team-form/team-form.component.ts
src/app/pages/team/team-list-sidenav/team-list-sidenav.component.html
src/app/shared/pipes/gt-pipes.module.ts
src/app/shared/pipes/trunc-ellipses-text.pipe.ts

Fix the messages 'task' instead of 'equipe'
Fix message 'equpe' to 'equipe' when message of error in team form
Add diff message for update and create tasks

Bugfix 193

---

src/app/pages/task/task-form/task-form.component.ts

Corrigindo problema no save da task.

Settando default null

---

src/app/core/interceptors/profiler.interceptor.ts
src/app/pages/task/task-grid/task-grid.component.ts
src/app/pages/team/team-detail/team-detail.component.ts

Closes #189 
The bug: 'Baixo' instead of 'Baixa'. To solve I used Enums.
Not it's working properly

Adjusting to get from Enum instead of string

---

.circleci/config.yml
src/app/pages/task/task-form/task-form.component.ts

Bugfix 204

---

.circleci/config.yml
src/app/pages/task/task-form/task-form.component.ts

Bugfix 185

---

.circleci/config.yml
src/app/pages/task/task-form/task-form.component.ts
src/app/pages/task/task-time-spent/task-time-spent.component.ts

Bugfix 207

---

src/app/pages/task/task-form/task-form.component.html
src/app/pages/task/task-form/task-form.component.ts

add targetUser to select in edit mode

---

src/_variables.scss
src/app/pages/home/due-soon-tasks/due-soon-tasks.component.html
src/app/pages/home/due-soon-tasks/due-soon-tasks.component.scss
src/app/pages/task/task-card/task-card.component.scss
src/app/shared/shared.module.ts
src/scss/status-indicator.scss

Closes #212 
- new layout of tags in 'Tasks em Alerta'
- refactoring scss files

Feature 212

---

src/app/pages/task/task-form/task-form.component.ts

Bugfix 180

---

src/app/pages/signup/signup.component.html
src/app/pages/signup/signup.component.ts
src/app/shared/shared.module.ts

Bugfix - #175

---

src/app/pages/task/task-form/task-form.component.html
src/app/pages/task/task-form/task-form.component.ts
src/app/pages/task/task-time-spent/task-time-spent.component.ts

Feature 179
